FROM node:20-alpine

WORKDIR /server

# Copy package files
COPY package*.json ./
RUN npm ci --omit=dev

# Copy source code
COPY . .

# Build for production
RUN npm run build

EXPOSE 9000 7001

CMD ["npm", "start"]
